language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh
env:
  - TEST=ci

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
      - secure: "cyT7LbrsyCWzqXQQrFLHDJ812iq9+5MeOq2DcG7uWkJdeSspHbI8WM+m++vtLNo1Q6J3k9ZITghJYNHxNeIJxTNnRzU1rlir+eZcfVdUiFJUTI1Cn8yeNmq9J5swaJ70fEotxTJEcN0BM6DqxXME19cv/oZKmcFu7l8zB0Xcv9E="
